### ISSUE TITLE
Question about hyperparameter

### ISSUE THREAD

**Issue by yccckid** [LiyuanLucasLiu/LightNER#8]
H en = α · Hen + (1 − α) · Eseq, from Eq. (6). How was this alpha set  in your code? Thank you

**Comment by nxllxvxxd** [comment]
# **DO NOT DOWNLOAD ANYTHING I HAVE POSTED AS A COMMENT MY ACCOUNT WAS COMPROMISED AND BEING USED TO COMPROMISE OTHERS**

**I AM WORKING ON DELETING AND POSTING THIS ON ALL THREADS IN WHICH THEY USED MY ACCOUNT TO POST THIS**
